apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: masktv-mysql-master
  labels:
    app: mysql-master
spec:
  serviceName: "masktv-mysql-master-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      role: master
  template:
    metadata:
      labels:
        app: mysql
        role: master
    spec:
      containers:
        - name: masktv-m-mysql-container
          image: masktv/masktv:mysql
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secrets 
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets  
                  key: MYSQL_USER 
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets 
                  key: MYSQL_PASSWORD
            - name: MYSQL_REPLICATION_MODE
              value: "master"
            - name: MYSQL_MASTER_HOST
              value: ""  # Empty because it's the master
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: master-configmap
              mountPath: /etc/mysql/my.cnf
              subPath: my.cnf
            - name: master-mysql-pv
              mountPath: /var/lib/mysql
            - name: mysql-log-pv
              mountPath: /var/log/mysql
      volumes:
        - name: master-configmap
          configMap:
            name: master-configmap
        - name: mysql-log-pv
          persistentVolumeClaim:
            claimName: mysql-log-pvc
  volumeClaimTemplates:
    - metadata:
        name: master-mysql-pv
      spec:
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: masktv-storage-class
        volumeMode: Filesystem
