apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-log-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""  # Use a specific storage class or leave empty for default
  resources:
    requests:
      storage: 5Gi  # Set according to application size
  volumeMode: Filesystem
  volumeName: mysql-log-pv  # To Schedule this pvc on app pv [app-log-pv]
