apiVersion: v1
kind: Service
metadata:
  name: proxysql
spec:
  ports:
    - name: mysql  # Name for the MySQL client port (default 3306)
      port: 3306
      targetPort: 3306
    - name: admin  # Name for the ProxySQL admin interface (port 6032)
      port: 6032
      targetPort: 6032
    - name: mysql-client  # Name for the ProxySQL MySQL client port (port 6033)
      port: 6033
      targetPort: 6033
  selector:
    app: proxysql
