# use env value in encoded formate
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
data: 
  MYSQL_ROOT_PASSWORD: <base64-encoded-root-password>
  MYSQL_DATABASE: <base64-encoded-database-name>
  MYSQL_USER: <base64-encoded-username>
  MYSQL_PASSWORD: <base64-encoded-user-password>
  MYSQL_MASTER_HOST: <base64-encoded-master-host>
