
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: masktv-mysql-slave
  labels:
    app: mysql-slave
spec:
  serviceName: "masktv-mysql-slave-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      role: slave
  template:
    metadata:
      labels:
        app: mysql
        role: slave
    spec:
      containers:
        - name: masktv-s-mysql-container
          image: masktv/masktv:mysql  # Replace with your custom image
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secrets 
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets  
                  key: MYSQL_USER 
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets 
                  key: MYSQL_PASSWORD
            - name: MYSQL_REPLICATION_MODE
              value: "slave"
            - name: MYSQL_MASTER_HOST
              value: "masktv-mysql-master-0.masktv-mysql-master-service"  # Name of the master pod             
            # if slave have more than 1 replica, then to set server id diff each replica use this config with slave-configmap with 2nd option
            #- name: MYSQL_SERVER_ID
             # valueFrom:
              #  fieldRef:
               #   fieldPath: metadata.name
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: slave-configmap
              mountPath: /etc/mysql/my.cnf
              subPath: my.cnf
            - name: slave-mysql-pv
              mountPath: /var/lib/mysql
            - name: mysql-log-pv
              mountPath: /var/log/mysql
      volumes:
        - name: slave-configmap
          configMap:
            name: slave-configmap
        - name: mysql-log-pv
          persistentVolumeClaim:
            claimName: mysql-log-pvc
  volumeClaimTemplates:
    - metadata:
        name: slave-mysql-pv
      spec:
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: masktv-storage-class
        volumeMode: Filesystem
