apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: masktv-storage-class  # Desired name for your EFS StorageClass
provisioner: efs.csi.aws.com      # The EFS provisioner for Kubernetes (EFS CSI Driver)
parameters:
  type: gp3
  fsType: ext4
reclaimPolicy: Retain             # Keeps the EFS filesystem even after PVC deletion
volumeBindingMode: WaitForFirstConsumer     # Volumes will be bound immediately to pods
allowVolumeExpansion: true  
